"use client";

import { Inter } from "next/font/google";
import Banner from "@/components/Banner";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "We love our king",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(true);

  const toggleSidebar = () => {
    setOpen(!open);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Banner />
        <Navbar toggleSidebar={toggleSidebar} />
        <main className="flex">
          {open && <Sidebar />}
          <div className={`${open && "ml-64"} mt-10`}>{children}</div>
        </main>
      </body>
    </html>
  );
}
